In [1]:
import numpy as np

In [2]:
X = np.array([[1,1,1,0,1,1,1,0,1,1,1,0,0,1,1,1,0,1,1,1,0]])
X_test = np.array([[1,0,1,0,1,0,0,0,1,0,1,0,0,1,1,0,0,0,1,0,0]])

In [3]:
def activation(x, theta = 0):
    if x>theta:
        return 1
    elif x<=theta:
        return 0

In [4]:
def hopfield_train(X_train):
    
    X = X_train
    w = X.T*X
    np.fill_diagonal(w, 0)
    X_bin = np.where(X >0, 1, 0)
    return w

In [5]:
def hopfield_test(X_test,w,check_same = 100):
    
    y=X_test.copy()
    Flag = False
    same = 0
    epochs = 0
    prev_y = np.zeros_like(y)

    while True:
        i = np.random.choice(range(len(y[0])))
        y[0,i] = X_test[0,i] + np.dot(y, w[:,i])
        y[0,i] = activation(y[0,i])
        print("Epoch - ",epochs ,"Place - ",i," Result :", y, "Same :", same)
        Flag = np.array_equal(y,prev_y)
        prev_y = y.copy()
        epochs = epochs +1
        if Flag == True:
            same += 1
            if same >= check_same:
                print('-----------------Execution Finished-----------')
                return y
                break
        else:
            same = 0


In [6]:
weights = hopfield_train(X)

In [7]:
output = hopfield_test(X_test,weights,30)

Epoch -  0 Place -  5  Result : [[1 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0]] Same : 0
Epoch -  1 Place -  4  Result : [[1 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0]] Same : 0
Epoch -  2 Place -  8  Result : [[1 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0]] Same : 1
Epoch -  3 Place -  9  Result : [[1 0 1 0 1 1 0 0 1 1 1 0 0 1 1 0 0 0 1 0 0]] Same : 2
Epoch -  4 Place -  3  Result : [[1 0 1 0 1 1 0 0 1 1 1 0 0 1 1 0 0 0 1 0 0]] Same : 0
Epoch -  5 Place -  15  Result : [[1 0 1 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0]] Same : 1
Epoch -  6 Place -  1  Result : [[1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0]] Same : 0
Epoch -  7 Place -  16  Result : [[1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0]] Same : 0
Epoch -  8 Place -  3  Result : [[1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0]] Same : 1
Epoch -  9 Place -  4  Result : [[1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0]] Same : 2
Epoch -  10 Place -  19  Result : [[1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 0]] Same : 3
Epoch -  11 Place -  16  Result : [[1 1

In [8]:
print(X,"\n",output)

[[1 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 0 1 1 1 0]] 
 [[1 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 0 1 1 1 0]]


In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(X[0],output[0])

In [10]:
cm

array([[ 6,  0],
       [ 0, 15]], dtype=int64)

In [11]:
print('Accuracy : ', (cm[0][0]+cm[1][1])/(cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1])*100,'%')

Accuracy :  100.0 %
